system.indexConfig.show_tongzhigonggao=false
system.indexConfig.show_daibanshiwu=false
system.indexConfig.show_gongzuojihua=false
system.indexConfig.show_gongzuorizhi=false
system.indexConfig.show_richenganpai=false
system.indexConfig.show_gerenkaoqin=false
system.indexConfig.show_gerenweishen=true
system.indexConfig.show_gerendaishen=false
system.indexConfig.show_myallcourses=true
system.indexConfig.show_myexams=false
system.indexConfig.show_mybuyrooms=true
system.indexConfig.show_mytrainingcourses=true
system.indexConfig.tongzhigonggao_length=3
system.indexConfig.daibanshiwu_length=4
system.indexConfig.gongzuojihua_length=4
system.indexConfig.gongzuorizhi_length=4
system.indexConfig.richenganpai_length=3
system.indexConfig.myallcourses_length=5
system.indexConfig.myexams_length=5
system.indexConfig.mybyrooms_length=5
system.indexConfig.mytrainingcourses_length=5
