system.scoreLogin=10.00
system.scoreLogin.per=0.10
system.scoreLoginNot3day.per=1.00
system.scoreWeek=10.00
system.scoreWeek.per=1.00
system.scoreClass=10.00
system.scoreClass.per=0.25
system.scoreProportionProcess=10.00
system.scoreProportionProcess.per=0.10
system.scoreProportionTime=10.00
system.scoreProportionTime.per=0.03
system.scoreRecodingProcess=10.00
system.scoreRecodingProcess.per=1.00
system.scoreRecodingTime=10.00
system.scoreRecodingTime.per=0.03
system.scoreExamPage=10.00
system.scoreExamPage.per=0.10
system.scoreExamCourse=20.00
system.scoreExamCourse1TO3.per=0.20
system.scoreExamCourse4TO6.per=0.13