system_jtm_open_jtm=false
system_jtm_my_evaluation_url=http\://182.18.31.226\:8081/kaihangtest/User_login.aspx
system_jtm_report_eval_url = http\://182.18.31.226\:8081/kaihangtest/ReportEval.aspx
system_jtm_peoplePost_url=http\://182.18.31.226\:8081/kaihanghrm/manage/PDjlcx2.aspx
system_jtm_my_report_url=http\://182.18.31.226\:8081/kaihanghrm/manage/ReportPD/reportbmself.aspx
system_jtm_courses_aynchronization_url=http\://182.18.31.226\:8081/kaihanghrm/Manage/courseinfo.aspx
system_jtm_my_cepingCourses_url=http\://182.18.31.226\:8081/kaihanghrm/Manage/getpushclass.aspx