##########sqlserver2005 configs
driverClass=net.sourceforge.jtds.jdbc.Driver
maxPoolSize=100
minPoolSize=2
acquireIncrement=2
user=sa
password=1
jdbcUrl=jdbc\:jtds\:sqlserver\://127.0.0.1\:1431;DatabaseName\=e_gdgat;SelectMethod\=cursor
checkouttimeout=10000
maxidletime =60
idleconnectiontestperiod=60
#jdbcUrl=jdbc\:jtds\:sqlserver\://210.51.174.182\:1431;DatabaseName\=elearning_;SelectMethod\=cursor
##########mysql configs
#driverClass=com.mysql.jdbc.Driver
#maxPoolSize=100
#minPoolSize=2
#acquireIncrement=2
#user=root
#password=1
#jdbcUrl=jdbc\:mysql\://localhost\:3306/elearning_qqhr?autoreconnect\=true



##########openmeetings
openmeetings.jdbcUrl=jdbc\:mysql\://localhost\:3306/openmeetings?autoreconnect\=true
openmeetings.user =root
openmeetings.password =1
