classman=com/sopia/classman/s_querySqls.sql
batchman=com/sopia/batchman/s_querySqls.sql
courseman=com/sopia/courseman/s_querySqls.sql
duman=com/sopia/duman/s_querySqls.sql
knowledgeman=com/sopia/knowledgeman/s_querySqls.sql
questionman=com/sopia/questionman/s_querySqls.sql
studyman=com/sopia/studyman/s_querySqls.sql
statman=com/sopia/statman/s_querySqls.sql
newsandmess=com/sopia/newsandmess/s_querySqls.sql
frontman=com/sopia/frontman/s_querySqls.sql
assistman=com/sopia/assistman/s_querySqls.sql
forumman=com/sopia/forumman/s_querySqls.sql
talentman=com/sopia/talentman/s_querySqls.sql
bookman=com/sopia/bookman/s_querySqls.sql
##sqlfile=s_querySqls.sql