##########mysql configs
driverClass=com.mysql.jdbc.Driver
maxPoolSize=100
minPoolSize=2
acquireIncrement=2
user=root
password=1
jdbcUrl=jdbc\:mysql\://localhost\:3306/e_wx?autoreconnect\=true
checkouttimeout=10000
maxidletime =60
idleconnectiontestperiod=60


##########openmeetings
openmeetings.jdbcUrl=jdbc\:mysql\://localhost\:3306/openmeetings?autoreconnect\=true
openmeetings.user =root
openmeetings.password =1
