classman=com/sopia/classman/querySqls.sql
batchman=com/sopia/batchman/querySqls.sql
courseman=com/sopia/courseman/querySqls.sql
duman=com/sopia/duman/querySqls.sql
knowledgeman=com/sopia/knowledgeman/querySqls.sql
questionman=com/sopia/questionman/querySqls.sql
studyman=com/sopia/studyman/querySqls.sql
statman=com/sopia/statman/querySqls.sql
newsandmess=com/sopia/newsandmess/querySqls.sql
frontman=com/sopia/frontman/querySqls.sql
assistman=com/sopia/assistman/querySqls.sql
forumman=com/sopia/forumman/querySqls.sql
talentman=com/sopia/talentman/querySqls.sql
bookman=com/sopia/bookman/querySqls.sql
##sqlfile=querySqls.sql