classman=com/sopia/classman/o_querySqls.sql
batchman=com/sopia/batchman/o_querySqls.sql
courseman=com/sopia/courseman/o_querySqls.sql
duman=com/sopia/duman/o_querySqls.sql
knowledgeman=com/sopia/knowledgeman/o_querySqls.sql
questionman=com/sopia/questionman/o_querySqls.sql
studyman=com/sopia/studyman/o_querySqls.sql
statman=com/sopia/statman/o_querySqls.sql
newsandmess=com/sopia/newsandmess/o_querySqls.sql
frontman=com/sopia/frontman/o_querySqls.sql
assistman=com/sopia/assistman/o_querySqls.sql
forumman=com/sopia/forumman/o_querySqls.sql
cms=com/sopia/cms/o_querySqls.sql
customreport=com/sopia/schedule/o_querySqls.sql
#talentman=com/sopia/talentman/querySqls.sql
#bookman=com/sopia/bookman/querySqls.sql
##sqlfile=querySqls.sql
zidingyi_template=com/sopia/schedule/zidingyi_template_querySqls.sql
wordman=com/sopia/wordman/o_querySqls.sql
