##########mysql configs
driverClass=oracle.jdbc.driver.OracleDriver
maxPoolSize=100
minPoolSize=2
initialpoolsize=10
acquireIncrement=2
user=WJM20160918
password=WjmOracle_2026_Local
jdbcUrl=jdbc:oracle:thin:@host.docker.internal:15211:XE
checkouttimeout=10000
maxidletime =60
idleconnectiontestperiod=60
 

##########openmeetings
 
openmeetings.driverClass=com.mysql.jdbc.Driver
openmeetings.jdbcUrl=jdbc\:mysql\://192.168.9.200\:3306/openmeetings_jnt?autoreconnect\=true
openmeetings.user =root
openmeetings.password =1
