#
#Thu Feb 16 15:47:30 CST 2012
stuff_url_local=1
system.conf.ctype.1=1
study.course.need.sh=false
forum.need.sh=true
coursemake.need.sh=false
study.class.need.sh=false
system.conf.database.type=oracle
shouye.url=\u65E0\u8BB0\u5F55
zhenshu.need.sh=false
openmeetings.admin.pwd=admin
study.course.ctype.z=0
study.course.ctype.x=0
stuff_size=0
openmeetings.url=http\://localhostopenmeetings.admin.user\=admin
knowledge.need.sh=false
study.course.ctype.b=0
system.conf.ctype.8=4
system.conf.register=1
system.conf.ctype.7=5
system.conf.ctype.6=4
system.conf.ctype.5=2
system.conf.ctype.4=3
stuff_url=http\://localhost\:8080/wjm/
shouye.img=\u65E0\u8BB0\u5F55
system.conf.ctype.3=2
register.need.sh=false
system.conf.ctype.2=1
system.conf.login.addip=0
stuff_op=false
stuff_isftopic=true
product_need_sh=true
shebei_need_sh=true
product_fabu_can_alter=true
product_baoxian_need_sh=true
line_training_course_add_need_sh=true
system.conf.registerinfo.isall=true
system.conf.userimp.ischeck=true
system_conf_https_port=9443
system_conf_http_port=9080
system.conf.office.size=10
system.conf.msg.username=sopiawkm
system.conf.msg.password=hlwzjc
system.conf.email.smtp=smtp.qq.com
system.conf.email.unames=1105157153@qq.com
system.conf.email.pwds=hlWzjC@610903
system.conf.email.sendcount=30
system.conf.yzcode.open=0
system.conf.office.home=C\:/Program Files (x86)/OpenOffice.org 3
system.conf.pdf2swf.path= C\:/Program Files (x86)/SWFTools/pdf2swf.exe
system.conf.allowMultipleSign=true
system.conf.is_enquiry_in_table=false
system_conf_login_max=0
system_conf_login_max_sd=0
system_conf_login_failure_max=0
learning.ks.cj=0.0
learning.xs.xs=3.0
learning.lx.lx=0.0
learning.mk.mk=0.0
learning.xf.xf=5.0
learning.bj.bj=0.0
learning.sc.sc=5.0
learning.btj.btj=0.0
learning.bxz.bxz=0.0
learning.xz.xz=0.0
learning.ft.ft=0.5
learning.fy.fy=0.1
learning.jh.jh=5.0
learning.dl.dl=0.1
index_classid=9
system_cong_is_receive_by_judge=true
model_working=0
publish_option=0
list_page_number=3
catalogue_place=/html
zdy_html=/zdyhtml
title_rule=1
system_release_question_need_sh=true
system_answer_question_need_sh=true
public_begin=elstuffs/1273/1371.wma
public_end=elstuffs/1273/1370.wma
public_end2=elstuffs/1273/1419.wma
sysconf.mac_need=false
sysconf.intelligentTutoringPoints=60
sysconf.similarity=60
sysconf.wjm=1
sysconf.ktxzSwf=elstuffs/1515/1519.swf
sysconf.kdhxzSwf=elstuffs/1515/1519.swf
sysconf.tyxtSwf=elstuffs/1515/1519.swf
sysconf.jsbySwf=elstuffs/1515/1519.swf
sysconf.tzSwf=elstuffs/1515/1519.swf
sysconf.pxSwf=elstuffs/1515/1519.swf
sysconf.ktxzEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.kdhxzEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.tyxtEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.jsbyEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.tzEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.pxEditorHtml=<p><strong>\u7B2C\u4E00\u6B65\uFF1A</strong> \u770B\u6765\u4F60\u4EEC\u516C\u53F8\u89C4\u6A21\u5F88\u5927\u554A\uFF01 </p>\r\n<p><strong>\u7B2C\u4E8C\u6B65\uFF1A</strong> \u6211\u4EEC\u6C49\u5546\u96C6\u56E2\u662F\u67DC\u5185\u89C4\u6A21\u6700\u5927\u7684\u65B0\u80FD\u6E90\u4F01\u4E1A\u4E4B\u4E00\u3002 <span style\="COLOR\: red">\uFF08 \uFF09</span> \u8D44\u4EA7\u603B\u989D\u5DF2\u7ECF\u8FBE\u5230957\u4EBF\u5143\u3002 </p>
sysconf.newShouye=0
sysconf.sd=1

