###############sql for Statistics######################
stat.user.course.list=select c.id,c.name,c.creater,eu.realname,c.credit,ca.status from COURSE_APPLY ca left join COURSE c on c.id = ca.courseid left join ELUSER eu on c.creater = eu.id where ca.userid = ?
stat.user.course.size = select count(*) from COURSE_APPLY ca where ca.userid = ? 
stat.course.bycreater = select c.id,c.name,ct.id,ct.name,c.credit,c.createtime,(select count(*) from course_apply ca where ca.valid = 1 and ca.courseid = c.id) as ucount,(select count(*) from study_course sc where sc.courseid= c.id and sc.passed = 1) as passcount from course c,course_type ct where c.ctypeid = ct.id and c.creater = ? 
stat.class.bycreater = select cl.id,cl.name,cl.createtime,(select count(*) from class_course ccb where ccb.status = 0 and ccb.classid=cl.id) as bxCount ,\
									(select count(*) from class_course ccx where ccx.status = 1 and ccx.classid=cl.id) as ccxCount ,\
									(select sum(ccx1.credit) from class_course ccx1 where ccx1.status=1 and ccx1.classid =cl.id ) as ccxCredit,optionalcredit,\
									(select count(*) from study_class ca where ca.classid = cl.id and ca.status = 2),(select count(*) from study_class scl where scl.classid = cl.id) as passedcount  from elclass cl where cl.creater = ?
stat.user.class.size = select count(*) from study_class ca where ca.userid = ? and ca.status = 2
stat.user.totalcredit= select sum(c.credit) as stuc from study_course sc , course c where  c.id = sc.courseid and sc.passed=1 and sc.userid= ?
########stat.user.class.list = select cl.id,cl.name,(select count(*) from class_course cc where cc.classid = cl.id and cc.status = 0) as bxCount, (select sum(cc.credit) from class_course cc where cc.classid = cl.id and cc.status = 1) as xxScore,ca.applydate from elclass cl,study_class ca where  ca.userid = ? and ca.classid = cl.id
stat.dep.user.credit=select * from (select eu.id,eu.realname,eu.username,dep.id depid ,dep.name ,sum(sc.mycredit) as  scredit,row_number() over( order by  sum(cc.credit)  desc ) rownum from eluser eu left join department dep on dep.id = eu.depid left join study_course sc on sc.userid = eu.id left join (select * from study_quizinfo where ispassed = 1 )sqi on  sqi.userid = eu.id left join exam_room er on  sqi.roomid =er.id  left join class_course cc on  er.courseid = cc.courseid where dep.lid>=? and dep.rid<= ? group by eu.id,eu.realname,eu.username,dep.id,dep.name ) t where t.rownum between ? and ?
stat.dep.user.credit.size=select count(*) from eluser eu,department dep where dep.id = eu.depid and dep.lid>=? and dep.rid<= ?
stat.class.view=select * from (select eu.id,   eu.realname,eu.username, dep.id depid,  dep.name,sqi.ispassed, cla.classid, sum(cc.credit) as credit ,cla.applyDate ,row_number() over(order by  sum(cc.credit) desc) rownum from eluser eu left join department dep on dep.id = eu.depid left join (select * from study_class where classid = ? and status=2 ) cla on cla.userid = eu.id left join (select * from study_quizinfo sqi where sqi.ispassed = 1 ) sqi on sqi.userid = eu.id  left   join exam_room er on sqi.roomid = er.id  left   join class_course cc on er.courseid = cc.courseid where  dep.lid>=? and dep.rid<=? group by eu.id,  eu.realname,  eu.username,  dep.id,      dep.name,  sqi.ispassed,  cla.classid,cla.applyDate) t where t.rownum between ? and ?
stat.class.view.size=select count(*) from eluser eu left join department dep on dep.id = eu.depid  where dep.lid>=? and dep.rid<=?
stat.user.dep.list.sub=select * from( select eu.id,eu.username, eu.realname,dep.id depid,dep.name, isnull(sum(sc.mycredit),0) as xfscore,row_number() over( order by isnull(sum(sc.mycredit),0)  desc) rownum  from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid = c.id where eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=?  group by eu.id,eu.username, eu.realname,dep.id,dep.name) t where t.rownum between ? and ?
stat.user.dep.list.sub.size=select count(*) from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=? 
stat.user.dep.list= select * from( select eu.id,eu.username, eu.realname,dep.id depid,dep.name, isnull(sum(sc.mycredit),0) as xfscore,row_number() over( order by isnull(sum(sc.mycredit),0)  desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid = c.id where eu.username like ? and eu.realname like ? and dep.id =?  group by eu.id,eu.username, eu.realname,dep.id,dep.name) t where t.rownum between ? and ? 
stat.user.dep.list.size=select count(*) from ELUSER eu left join DEPARTMENT  dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and dep.id=?
stat.talent.dep.list.sub=select * from (select xuehao,studentno,danweihao,realname,  username,password,kuaijihao,renyuanleibie,zhichengleibie,zhichengjibie,lianxifangshi, sex,minzu,peixunleibie,shifouzaizhi,suozaigangwei,biyeyuanxiao,biyeshijian,suoxuezhuanye, xueli,xuewei,zhichenghao,zhiwupinrenriqi,zhichengquderiqi,beizhu,headphoto ,eu.id euid,dep.id depid,dep.name,row_number() over(order by dep.id asc) rownum \
 from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id  where eu.username like ?  and eu.realname like ?  and eu.zhichengleibie like ?  and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ? and eu.sex  like ? and eu.peixunleibie like ?  and dep.lid >=? and dep.rid<=? )t where t.rownum between  ? and ?
stat.talent.dep.list.sub.size=select COUNT(*) from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id  where eu.username like ? and eu.realname like ? and eu.zhichengleibie like ? and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ?   and eu.sex  like ? and eu.peixunleibie like ? and dep.lid >=?   and dep.rid<=?
stat.talent.dep.list=select * from (select xuehao,studentno,danweihao,realname,  username,password,kuaijihao,renyuanleibie,zhichengleibie,zhichengjibie,lianxifangshi, sex,minzu,peixunleibie,shifouzaizhi,suozaigangwei,biyeyuanxiao,biyeshijian,suoxuezhuanye,\
	xueli,xuewei,zhichenghao,zhiwupinrenriqi,zhichengquderiqi,beizhu,headphoto ,eu.id euid ,dep.id depid,dep.name,row_Number() over(order by dep.id asc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and eu.zhichengleibie like ? and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ? and eu.sex like ? and eu.peixunleibie like ?  and dep.id =? 				 ) t where t.rownum between ? and ?
stat.talent.dep.list.size= select COUNT(*)  from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id  where eu.username like ? and eu.realname like ? and eu.zhichengleibie like ? and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ? and eu.sex like ? and eu.peixunleibie like ? and dep.id =? 
stat.talent.dep.list.sub.all= select * from (select xuehao,studentno,danweihao,realname, username,password,kuaijihao,renyuanleibie,zhichengleibie,zhichengjibie,lianxifangshi, sex,minzu,peixunleibie,shifouzaizhi,suozaigangwei,biyeyuanxiao,biyeshijian,suoxuezhuanye,xueli,xuewei,zhichenghao,zhiwupinrenriqi,zhichengquderiqi,beizhu,headphoto ,eu.id euid,dep.id depid,dep.name,row_number() over(order by dep.id asc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and eu.zhichengleibie like ? and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ? and eu.sex  like ? and eu.peixunleibie like ? and dep.lid >=? and dep.rid<=? )t
stat.talent.dep.list.all= select * from (select xuehao,studentno,danweihao,realname,username,password,kuaijihao,renyuanleibie,zhichengleibie,zhichengjibie,lianxifangshi,sex,minzu,peixunleibie,shifouzaizhi,suozaigangwei,biyeyuanxiao,biyeshijian,suoxuezhuanye,xueli,xuewei,zhichenghao,zhiwupinrenriqi,zhichengquderiqi,beizhu,headphoto ,eu.id euid ,dep.id depid,dep.name,row_Number() over(order by dep.id asc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and eu.zhichengleibie like ? and eu.renyuanleibie like ? and eu.suozaigangwei like ? and eu.age like ? and eu.sex like ? and eu.peixunleibie like ? and dep.id =? ) t

stat.ctime.user.dep.sub=select * from(	select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(c.during),0) as t_time,isnull(sum(sc.passtime/60),0)as x_time ,isnull(sum(c.credit),0) as t_credit,isnull(sum(sc.mycredit ),0)as x_score ,	row_number() over(order by isnull(sum(sc.passtime/60),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid =c.id where   eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=? group by eu.id,eu.username, eu.realname, dep.id,dep.name ) t where t.rownum between ? and ?
stat.ctime.user.dep= select * from(	select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(c.during),0) as t_time,isnull(sum(sc.passtime/60),0)as x_time ,isnull(sum(c.credit),0) as t_credit,isnull(sum(sc.mycredit ),0)as x_score ,	row_number() over(order by isnull(sum(sc.passtime/60),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid =c.id where eu.username like ? and eu.realname like ? and dep.id=? group by eu.id,eu.username, eu.realname, dep.id,dep.name) t where t.rownum between ? and ?

stat.ctime.user.dep.sub.size= select count(*) from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=?
stat.ctime.user.dep.size=select count(*) from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id where eu.username like ? and eu.realname like ? and dep.id=?
 
stat.ctime.user.dep.sub.all=select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(c.during),0) as t_time,isnull(sum(sc.passtime/60),0)as x_time ,isnull(sum(c.credit),0) as t_credit,isnull(sum(sc.mycredit ),0)as x_score ,	row_number() over(order by isnull(sum(sc.passtime/60),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid =c.id where   eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=? group by eu.id,eu.username, eu.realname, dep.id,dep.name
stat.ctime.user.dep.all=select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(c.during),0) as t_time,isnull(sum(sc.passtime/60),0)as x_time ,isnull(sum(c.credit),0) as t_credit,isnull(sum(sc.mycredit ),0)as x_score ,	row_number() over(order by isnull(sum(sc.passtime/60),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join study_course sc on sc.userid = eu.id left join course c on sc.courseid =c.id where   eu.username like ? and eu.realname like ? and dep.id =? group by eu.id,eu.username, eu.realname, dep.id,dep.name
stat.cnote.user.dep.sub=select * from ( select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(cn.score),0) as t_credit,row_number() over(order by isnull(sum(cn.score),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join course_note cn on cn.userid = eu.id left join course c on cn.courseid =c.id where   eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=? group by eu.id,eu.username, eu.realname, dep.id,dep.name ) t where t.rownum between ? and ? 
stat.cnote.user.dep= select * from (  select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull(sum(cn.score),0) as t_credit,row_number() over(order by isnull(sum(cn.score),0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join course_note cn on cn.userid = eu.id left join course c on cn.courseid =c.id where   eu.username like ? and eu.realname like ? and dep.id=? group by eu.id,eu.username, eu.realname, dep.id,dep.name  ) t where t.rownum between ? and ? 

stat.ucredit.user.dep.sub=select * from ( select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull( cn.t_score,0) as t_credit,isnull (sc.t_credit,0) as sc_score,isnull(sqi.sqi_score,0) sqi_score,isnull(o.o_score,0) o_score,isnull(sqi2.sqi2_score,0) sqi2_score, row_number() over(order by isnull( cn.t_score,0)+isnull( cn.t_score,0)+isnull (sc.t_credit,0)+isnull(sqi.sqi_score,0)+isnull(o.o_score,0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join (select sum(score) t_score,userid from  course_note group by userid)cn on cn.userid = eu.id left join (select sum(mycredit) t_credit,userid from study_course group by userid ) sc on sc.userid = eu.id left join (select sum(sqi1.score) sqi_score,sqi1.userid from study_quizinfo sqi1 left join exam_room er on er.id = sqi1.roomid where er.iscommon=1 group by sqi1.userid ) sqi on sqi.userid = eu.id left join (select sum(o1.score) o_score,o2u.userid from eloffline o1 right join eloffline2user o2u on o2u.offid = o1.id group by o2u.userid ) o on o.userid = eu.id left join (select sum(sqi1.score) sqi2_score,sqi1.userid from study_quizinfo sqi1 left join exam_room er on er.id = sqi1.roomid where er.iscommon=0 group by sqi1.userid ) sqi2 on sqi2.userid = eu.id where eu.username like ? and eu.realname like ? and dep.lid >=? and dep.rid<=? group by eu.id,eu.username, eu.realname, dep.id,dep.name,cn.t_score,sc.t_credit,sqi.sqi_score,o.o_score,sqi2.sqi2_score ) t where t.rownum between ? and ?
stat.ucredit.user.dep=select * from ( select eu.id,eu.username, eu.realname,dep.id depid,dep.name,isnull( cn.t_score,0) as t_credit,isnull (sc.t_credit,0) as sc_score,isnull(sqi.sqi_score,0) sqi_score,isnull(o.o_score,0) o_score,isnull(sqi2.sqi2_score,0) sqi2_score, row_number() over(order by iisnull( cn.t_score,0)+isnull( cn.t_score,0)+isnull (sc.t_credit,0)+isnull(sqi.sqi_score,0)+isnull(o.o_score,0) desc) rownum from ELUSER eu left join DEPARTMENT dep on eu.depid = dep.id left join (select sum(score) t_score,userid from  course_note group by userid)cn on cn.userid = eu.id left join (select sum(mycredit) t_credit,userid from study_course group by userid ) sc on sc.userid = eu.id left join (select sum(sqi1.score) sqi_score,sqi1.userid from study_quizinfo sqi1 left join exam_room er on er.id = sqi1.roomid where er.iscommon=1 group by sqi1.userid ) sqi on sqi.userid = eu.id left join (select sum(o1.score) o_score,o2u.userid from eloffline o1 right join eloffline2user o2u on o2u.offid = o1.id group by o2u.userid ) o on o.userid = eu.id left join (select sum(sqi1.score) sqi2_score,sqi1.userid from study_quizinfo sqi1 left join exam_room er on er.id = sqi1.roomid where er.iscommon=0 group by sqi1.userid ) sqi2 on sqi2.userid = eu.id where eu.username like ? and eu.realname like ? and dep.id=? group by eu.id,eu.username, eu.realname, dep.id,dep.name,cn.t_score,sc.t_credit,sqi.sqi_score,o.o_score,sqi2.sqi2_score ) t where t.rownum between ? and ?



######stat.dep.course.size=select count(distinct(c.id)) from COURSE_APPLY ca left join COURSE c on c.id = ca.courseid left join ELUSER eu on c.creater = eu.id left join ELUSER eu_s on eu_s.id = ca.userid left join DEPARTMENT dep on eu_s.depid = dep.id where eu_s.depid = ? 
#######stat.dep.user.size=select count(*) from ELUSER eu_s left join DEPARTMENT dep on eu_s.depid = dep.id where eu_s.depid = ?  
stat.dep.course.list=select distinct(c.id),c.name,c.creater,eu.realname,c.credit, c.createtime from study_course ca left join COURSE c on c.id = ca.courseid left join ELUSER eu on c.creater = eu.id left join ELUSER eu_s on eu_s.id = ca.userid left join DEPARTMENT dep on eu_s.depid =dep.id where eu_s.depid = ? 
stat.dep.info.bydid = select dep.id ,dep.name ,(select count(*) from eluser eu where eu.depid = dep.id ) as usercount,\
					(select count(distinct (ca.courseid)) from course_apply ca,eluser caeu where caeu.depid = dep.id and caeu.id = ca.userid ),\
					(select count(distinct(cla.classid)) from study_class cla,eluser claeu where claeu.depid = dep.id and claeu.id = cla.userid  ) from department dep , department depp  where dep.lid >depp.lid and dep.rid <depp.rid and depp.id= ? 
stat.dep.info.byid = select dep.id ,dep.name ,(select count(*) from eluser eu where eu.depid = dep.id ) as usercount,\
					(select count(distinct (ca.courseid)) from course_apply ca,eluser caeu where caeu.depid = dep.id and caeu.id = ca.userid ),\
					(select count(distinct(cla.classid)) from study_class cla,eluser claeu where claeu.depid = dep.id and claeu.id = cla.userid  ) from department dep , department depp  where dep.lid >depp.lid and dep.rid <depp.rid and dep.id = ? 
stat.dep.class.list = select distinct(cl.id),cl.name,euc.id,euc.realname,optionalcredit,createtime,(select count(*) from class_course ccb where ccb.status = 0 and ccb.classid=cl.id) as bxCount ,\
									(select count(*) from class_course ccx where ccx.status = 1 and ccx.classid=cl.id) as ccxCount ,\
									(select sum(ccx1.credit) from class_course ccx1 where ccx1.status=1 and ccx1.classid =cl.id ) as ccxCredit \
									 from elclass cl,eluser euc,study_class cla,eluser eus where cl.creater = euc.id and eus.id = cla.userid and cla.classid = cl.id and eus.depid = ?
									
####stat.course.list=select c.id, c.name,c.ctypeid,c.createtime,ct.name from COURSE c left join COURSE_TYPE ct on c.ctypeid = ct.id where c.name like ?
stat.course.list.bytid= select c.id, c.name cname,c.ctypeid,c.createtime,ct.name ctname,count(sc.userid) sccount from COURSE c left join COURSE_TYPE ct on c.ctypeid = ct.id left join study_course sc on sc.courseid = c.id where c.name like ? and  ct.lid>=? and ct.rid<=? group by  c.id, c.name,c.ctypeid,c.createtime,ct.name

stat.course.list.sub.bytid=select c.id, c.name,c.ctypeid,c.createtime,ct.name,(select count(*) from course_apply ca where ca.courseid = c.id ) from COURSE c left join COURSE_TYPE ct on c.ctypeid = ct.id  where c.name like ? and c.ctypeid=?
stat.course.user.list= select eu.id, eu.username,eu.realname,eu.depid,dep.name depname ,c.credit, c.during, sc.passtime/60 passtime,sc.process,sc.status,sc.mycredit,sqi.id _sqiid,sqi.myScore,sqi.ispassed from study_course sc left join course c on sc.courseid = c.id left join eluser eu on sc.userid = eu.id left join department dep on dep.id = eu.depid left join study_quizinfo sqi on sqi.id=sc.sqiid where sc.courseid =?


stat.simexam.didandepid = select sep.epid , sep.courseid ,c.name,c.creater,eu_c.realname,ep.title from SIMEXAMPAPER sep,COURSE c,ELUSER eu_c,EXAMPAPER ep where sep.courseid in (select ca.courseid from COURSE_APPLY ca,ELUSER eu where eu.depid = ?) and sep.courseid = c.id and eu_c.id = c.creater and sep.epid = ep.id

stat.offline.query.byid=select o.id, o.name,o.description,o.during,o.xueshi,o.score,o.begintime,o.endtime,count(ou.userid) ouuser from eloffline o left join eloffline2user ou on ou.offid = o.id where o.id = ? group by  o.id, o.name,o.description,o.during,o.xueshi,o.score,o.begintime,o.endtime
stat.offline.user.list=select eu.id euid,eu.realname,eu.username,eu.sex,dep.id depid,dep.name depname  from eluser eu left join eloffline2user ou on ou.userid=eu.id left join department dep on dep.id = eu.depid where ou.offid=?
